export const PROVINCIAS_POR_COMUNIDAD: { [key: string]: string[] } = {
  'Andalucía': ['Sevilla', 'Málaga', 'Córdoba', 'Granada', 'Huelva', 'Jaén', 'Cádiz', 'Almería'],
  'Aragón': ['Zaragoza', 'Huesca', 'Teruel'],
  'Asturias': ['Oviedo'],
  'Baleares': ['Mallorca', 'Menorca', 'Ibiza', 'Formentera'],
  'Canarias': ['Las Palmas', 'Santa Cruz de Tenerife'],
  'Cantabria': ['Santander'],
  'Castilla y León': ['León', 'Valladolid', 'Burgos', 'Salamanca', 'Zamora', 'Segovia', 'Soria', 'Ávila', 'Palencia'],
  'Castilla-La Mancha': ['Toledo', 'Albacete', 'Ciudad Real', 'Guadalajara', 'Cuenca'],
  'Cataluña': ['Barcelona', 'Tarragona', 'Girona', 'Lleida'],
  'Comunidad Valenciana': ['Valencia', 'Alicante', 'Castellón'],
  'Extremadura': ['Badajoz', 'Cáceres'],
  'Galicia': ['A Coruña', 'Lugo', 'Ourense', 'Pontevedra'],
  'Madrid': ['Madrid'],
  'Murcia': ['Murcia'],
  'Navarra': ['Pamplona'],
  'País Vasco': ['Álava', 'Vizcaya', 'Guipúzcoa'],
  'La Rioja': ['Logroño'],
  'Ceuta': ['Ceuta'],
  'Melilla': ['Melilla']
};
